### ISSUE TITLE
Problem With Map Creation

### ISSUE THREAD

**Issue by OneTiredSlav** [James-Fire/Factorio-Tiberium#16]
Whenever I try to make a world I get the following error message: 

"The mod Factorio and Conquer: Tiberian Dawn caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Factorio-Tiberium::on_init()
The mod Set Spawn caused a non-recoverable error.
Please report this error to the mod author.

Error while running event setspawn::on_force_created (ID 27)
__setspawn__/control.lua:30: attempt to call field 'get_spawn_position' (a nil value)
stack traceback:
	__setspawn__/control.lua:30: in function <__setspawn__/control.lua:27>
stack traceback:
	__Factorio-Tiberium__/control.lua:87: in function <__Factorio-Tiberium__/control.lua:8>
stack traceback:
	[C]: in function 'create_force'
	__Factorio-Tiberium__/control.lua:87: in function <__Factorio-Tiberium__/control.lua:8>"

What does all of this mean and how can I fix it?

**Comment by James-Fire** [comment]
Not our mod, reported to actual mod author, he has promised a fix.
