### ISSUE TITLE
SRF Emitter Hub does not "activate" if placed by bots

### ISSUE THREAD

**Issue by cvl43177** [James-Fire/Factorio-Tiberium#18]
Replication attempt:
Place SRF hubs  and make sure the sonic fence is activated.
Destroy the hubs through means that leave a ghost
Have bots replace the SRF hubs

SRF hubs do not activate the sonic fence.  Current manual fix is by replacing the SRF hub by hand.

**Comment by James-Fire** [comment]
This is now fixed in the live Portal version.
