### ISSUE TITLE
Missing a key definintion

### ISSUE THREAD

**Issue by WindowsPSAdmin** [James-Fire/Factorio-Tiberium#19]
![image](https://user-images.githubusercontent.com/26104461/77514708-03398200-6ec3-11ea-8227-c38da29c2a7d.png)

**Comment by James-Fire** [comment]
Oh, well then. Fixed for next release.

**Comment by WindowsPSAdmin** [comment]
Here's another ;)
![image](https://user-images.githubusercontent.com/26104461/77516168-9ffd1f00-6ec5-11ea-8969-20cc92021341.png)

**Comment by James-Fire** [comment]
That one shouldn't be visible...

Regardless, will be fixed.

**Comment by WindowsPSAdmin** [comment]
Another key missing my dude
![image](https://user-images.githubusercontent.com/26104461/78340159-f14d9280-75d8-11ea-92a3-06dd878f4856.png)
