### ISSUE TITLE
Getting nailed by tiberium even though i'm not on a field

### ISSUE THREAD

**Issue by WindowsPSAdmin** [James-Fire/Factorio-Tiberium#20]
![image](https://user-images.githubusercontent.com/26104461/77521872-0fc3d780-6ecf-11ea-9eeb-93862a3e173b.png)
![image](https://user-images.githubusercontent.com/26104461/77521889-15b9b880-6ecf-11ea-91da-483ce0fef5d5.png)
![image](https://user-images.githubusercontent.com/26104461/77521896-18b4a900-6ecf-11ea-920d-d887af9b3080.png)

**Comment by James-Fire** [comment]
Nodes damage players in a radius slightly larger than their max growth range, which is by default 30.
