### ISSUE TITLE
Placed a thing and it went boom

### ISSUE THREAD

**Issue by WindowsPSAdmin** [James-Fire/Factorio-Tiberium#21]
![image](https://user-images.githubusercontent.com/26104461/77904004-23a07c80-72c7-11ea-9491-86a18b0112ee.png)

The most helpful issue description, ever.

**Comment by James-Fire** [comment]
You're using construction drones, aren't you?

I think this error might not be mine to fix. But I'll look.

**Comment by James-Fire** [comment]
This is now fixed in the live version. Closing.
