### ISSUE TITLE
I have another key missing, linked to previous issue.

### ISSUE THREAD

**Issue by WindowsPSAdmin** [James-Fire/Factorio-Tiberium#22]
Another key missing my dude
![image](https://user-images.githubusercontent.com/26104461/78340159-f14d9280-75d8-11ea-92a3-06dd878f4856.png)

_Originally posted by @WindowsPSAdmin in https://github.com/James-Fire/Factorio-Tiberium/issues/19#issuecomment-608302769_

**Comment by James-Fire** [comment]
Uh... that's not me. Klonan's Transport drones?
