### ISSUE TITLE
Crash on tick 

### ISSUE THREAD

**Issue by hanakocz** [James-Fire/Factorio-Tiberium#43]
> Error while running event Factorio-Tiberium::on_tick (ID 0)
> __Factorio-Tiberium__/scripts/CnC_Walls.lua:267: attempt to compare nil with number
> stack traceback:
> 	__Factorio-Tiberium__/scripts/CnC_Walls.lua:267: in function 'CnC_SonicWall_OnTick'
> 	__Factorio-Tiberium__/control.lua:487: in function <__Factorio-Tiberium__/control.lua:458>
> 14179.101 Error ClientMultiplayerManager.cpp:98: MultiplayerManager failed: "Modifikace Factorio and Conquer: Tiberian Dawn (0.1.12) zpĹŻsobila neopravitelnĂ˝ error.
> ProsĂ­m nahlaste tento error autorovi modifikace.
> 
> Error while running event Factorio-Tiberium::on_tick (ID 0)
> __Factorio-Tiberium__/scripts/CnC_Walls.lua:267: attempt to compare nil with number
> stack traceback:
> 	__Factorio-Tiberium__/scripts/CnC_Walls.lua:267: in function 'CnC_SonicWall_OnTick'
> 	__Factorio-Tiberium__/control.lua:487: in function <__Factorio-Tiberium__/control.lua:458>"

version 0.1.12

Eye witnesses think that it happened because tiberium rocket did hit the frequency barrier.

Edit: any AoE damage done to tiberium walls causes the crash (grenade, rocket, splash rocket, rifle ammo with AoE effect, tank shell, artillery sheel, etc...)

**Comment by James-Fire** [comment]
This has been fixed, closing.
