### ISSUE TITLE
Crash on PlaceOre

### ISSUE THREAD

**Issue by Quadrum1** [James-Fire/Factorio-Tiberium#44]
![unknown](https://user-images.githubusercontent.com/38959426/86536742-3cce5000-beea-11ea-9999-2c6480012c5a.png)

Once encountered, the crash happened time and time again, ending the current map.

Edit: Map was only tried a single time after the first crash, might have been fixed after that or a rare occurence with a bit of bad luck

**Comment by James-Fire** [comment]
If you could provide the save, that would really help in tracking down the issue.

**Comment by Quadrum1** [comment]
#43 happened on the same map/server.
I saw on the discord that they will host the map again, so you get the ~50mb savefile.

**Comment by James-Fire** [comment]
Okay, this has been fixed. Closing.
