### ISSUE TITLE
Non-recoverable error when Construction Drone builds a blueprint ghost

### ISSUE THREAD

**Issue by paul-oreilly-nz** [James-Fire/Factorio-Tiberium#78]
![image](https://user-images.githubusercontent.com/36577283/90329597-52ab5680-dffa-11ea-9176-fa785ba11095.png)

Mod version: Tiberian Dawn 1.0.2
Event: on_entity_destroyed
Error: __Factorio-Tiberium__/control.lua:817 attempt to index local 'entity' (a nil value)
Stack: lines 817, 815

Triggered by construction drones (mod unit, cheap ground based construction drone) building thermal solar panels (another mod), as seen in the background of the screen. During the build, they are replacing ghosts, and it appears that the ghost being removed  may have triggered the above error.

[mod-list.json.txt](https://github.com/James-Fire/Factorio-Tiberium/files/5080226/mod-list.json.txt)

**Comment by James-Fire** [comment]
We fixed this in some version.

**Comment by randomflyingtaco** [comment]
1.0.3, if anyone is curious
