### ISSUE TITLE
Growth Accelerators need to affect growth with their credits.

### ISSUE THREAD

**Issue by James-Fire** [James-Fire/Factorio-Tiberium#8]
Growth accelerators can be placed, and have growth credits placed in them. They need to affect growth now.

**Comment by randomflyingtaco** [comment]
I came here to report this issue as well after feeding 200 credits to a Growth Accelerator with no visible effect.

**Comment by James-Fire** [comment]
Did you wait for the regular growth to happen? Feeding the credits in does not do anything immediately, it boosts growth when the cycle happens.

**Comment by jons-aura** [comment]
There should be a growth cycle every 5 minutes so give it at least this long.

**Comment by randomflyingtaco** [comment]
I waited 2+ hours, the patch stayed at 10M and the nodes stayed at 45M.  It's possible that there was growth of less than .5M?

**Comment by torndar** [comment]
200 credits would be *way* less. They're meant more as a resource recycling route for things that you have too much of rather than hundreds of chests or voiding the resources. They are intentionally lossy and you won't get back what you put into them.

**Comment by James-Fire** [comment]
Each node, over 2 hours, should make about 12k. 200 growth credits will only add 20k.

Tiles of tiberium also have a max value of 10000, and 10 mil sounds around that limit for the number of tiles.
