### ISSUE TITLE
Compatibility with K2 & SE

### ISSUE THREAD

**Issue by achman741** [James-Fire/Factorio-Tiberium#83]
The seems to be issues with compatibility with Krastorio 2 and Space Exploration mods with the varying tiberium separation recipes:

https://imgur.com/a/sZ5uG5S

![fbug 1](https://user-images.githubusercontent.com/4545011/124291105-346f1c00-db22-11eb-8ca8-e7e006843186.png)

https://imgur.com/a/uxxI04B

![fbug 2](https://user-images.githubusercontent.com/4545011/124291123-3afd9380-db22-11eb-81df-cee7f30ab1ea.png)

Don't know if this is fixable or not, may be on their end.  Also some the recipes that turn molten tiberium in SE's resources may need balanced, Naquitite gives 64 of them for example.

**Comment by James-Fire** [comment]
I'll just... close this cause it's really old.
